spring.application.name=sifap-backend

spring.datasource.url=${SIFAP_DB_URL:jdbc:postgresql://localhost:5432/sifap}
spring.datasource.username=${SIFAP_DB_USER:sifap}
spring.datasource.password=${SIFAP_DB_PASS:sifap}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.hibernate.SQL=DEBUG
